#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Oct 10, 2018 05:07:17 PM EDT  platform: Windows NT
import pandas as pd
import numpy as np
import sys
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global entry
    entry = StringVar()
    global var2
    var2 = StringVar()
    global var3
    var3 = StringVar()
    global var1
    var1 = StringVar()
    global var4
    var4 = StringVar()
    global var5
    var5 = StringVar()
    global var6
    var6 = StringVar()
    global listvar
    listvar = StringVar()

def print_school():
    county_name=entry.get()
    for i in range(40):
        w.Listbox1.insert(0,"")
    df=pd.read_csv("School_Data_Combined.csv")
    npdf = np.array(df)#np.ndarray()
    list=npdf.tolist()#list
    row=0
    for i in range(len(list)):
        if list[i][11]+'-County'==county_name or list[i][11]==county_name:
            w.Listbox1.insert(0,("School Name: "+list[i][7]+" County Name: "+list[i][11]))
            w.Listbox1.insert(1,("Advanced Percent: "+str(list[i][3])+"  Proficient Percent: "+str(list[i][4])+"  Basic Percent: "+str(list[i][5])+"  Below Basic Percent: "+str(list[i][6])))
            w.Listbox1.insert(2,("School Safety: "))
            w.Listbox1.insert(3,("Assaults on Staff: "+str(list[i][8])+"  Assaults on Students: "+str(list[i][9])+"  Conduct OSS: "+str(list[i][10])+"  Enrollment: "+str(list[i][11])))
            w.Listbox1.insert(4,'')
            w.Listbox1.insert(5,'')
    sys.stdout.flush()

def print_selection1():
    county_name=entry.get()
    for i in range(30):
        w.Listbox1.insert(0,"")
    df=pd.read_csv("ethnicity.csv")
    npdf = np.array(df)#np.ndarray()
    list=npdf.tolist()#list
    row=0
    for i in range(len(list)):
        if list[i][10]==county_name:
            w.Listbox1.insert(row,("City Name: "+list[i][1]))
            row=row+1
        if list[i][1]==county_name:
            w.Listbox1.insert(0,("City Name: "+list[i][1]+"  County Name: "+list[i][10]))
            w.Listbox1.insert(1,("Population: "+str(list[i][2])+"  Age: "+str(list[i][3])+"  Average Income: "+str(list[i][4])))
            w.Listbox1.insert(2,("Percent of Men in City: "+str(list[i][5])+"%  Per Capita Income: "+str(list[i][7])+"  Median House Value: "+str(list[i][8])))
            w.Listbox1.insert(3,("Zip Code: "+str(list[i][14])+"  Latitude: "+str(list[i][15])+"  Longitude: "+str(list[i][16])))
            w.Listbox1.insert(4,("Higher Degree: "+str(list[i][11])+"  H.S Diploma: "+str(list[i][12])+"  No H.S Diploma: "+str(list[i][13])))
    sys.stdout.flush()

def print_selection2():
    for i in range(30):
        w.Listbox1.insert(0,"")
    if(var1.get()=='1'):
        df=pd.read_csv("ethnicity.csv")
        list1=[]
        for i in range(5):
            n=df[df['Population'].isin([max(df['Population'])])]
            npdf = np.array(n)
            list=npdf.tolist()
            list1.append(list[0][1])
#            w.Listbox1.insert(0,list[0][1])
            a = df[(df['City']==list[0][1])].index.tolist()
            df=df.drop(a)
        w.Listbox1.insert(0,"Top 5 cities with most Population:")
        w.Listbox1.insert(1,("1."+list1[0]+"  2."+list1[1]+"  3."+list1[2]+"  4."+list1[3]+"  5."+list1[4]+"  "))
        w.Listbox1.insert(2,'')
    if(var2.get()=='1'):
        df=pd.read_csv("ethnicity.csv")
        list1=[]
        for i in range(5):
            n=df[df['Age'].isin([max(df['Age'])])]
            npdf = np.array(n)
            list=npdf.tolist()
            list1.append(list[0][1])
#            w.Listbox1.insert(0,list[0][1])
            a = df[(df['City']==list[0][1])].index.tolist()
            df=df.drop(a)
        w.Listbox1.insert(0,"Top 5 cities with most Age:")
        w.Listbox1.insert(1,("1."+list1[0]+"  2."+list1[1]+"  3."+list1[2]+"  4."+list1[3]+"  5."+list1[4]+"  "))
        w.Listbox1.insert(2,'')
    if(var3.get()=='1'):
        df=pd.read_csv("ethnicity.csv")
        list1=[]
        for i in range(5):
            n=df[df['Average Income'].isin([max(df['Average Income'])])]
            npdf = np.array(n)
            list=npdf.tolist()
            list1.append(list[0][1])
#            w.Listbox1.insert(0,list[0][1])
            a = df[(df['City']==list[0][1])].index.tolist()
            df=df.drop(a)
        w.Listbox1.insert(0,"Top 5 cities with most Average Income:")
        w.Listbox1.insert(1,("1."+list1[0]+"  2."+list1[1]+"  3."+list1[2]+"  4."+list1[3]+"  5."+list1[4]+"  "))
        w.Listbox1.insert(2,'')
    if(var4.get()=='1'):
        df=pd.read_csv("ethnicity.csv")
        list1=[]
        for i in range(5):
            n=df[df['Percent of Men in City'].isin([max(df['Percent of Men in City'])])]
            npdf = np.array(n)
            list=npdf.tolist()
            list1.append(list[0][1])
#            w.Listbox1.insert(0,list[0][1])
            a = df[(df['City']==list[0][1])].index.tolist()
            df=df.drop(a)
        w.Listbox1.insert(0,"Top 5 cities with most Percent of Men in City:")
        w.Listbox1.insert(1,("1."+list1[0]+"  2."+list1[1]+"  3."+list1[2]+"  4."+list1[3]+"  5."+list1[4]+"  "))
        w.Listbox1.insert(2,'')
    if(var5.get()=='1'):
        df=pd.read_csv("ethnicity.csv")
        list1=[]
        for i in range(5):
            n=df[df['Per Capita Income'].isin([max(df['Per Capita Income'])])]
            npdf = np.array(n)
            list=npdf.tolist()
            list1.append(list[0][1])
#            w.Listbox1.insert(0,list[0][1])
            a = df[(df['City']==list[0][1])].index.tolist()
            df=df.drop(a)
        w.Listbox1.insert(0,"Top 5 cities with most Per Capita Income:")
        w.Listbox1.insert(1,("1."+list1[0]+"  2."+list1[1]+"  3."+list1[2]+"  4."+list1[3]+"  5."+list1[4]+"  "))
        w.Listbox1.insert(2,'')
    if(var6.get()=='1'):
        df=pd.read_csv("ethnicity.csv")
        list1=[]
        for i in range(5):
            n=df[df['Median House Value'].isin([max(df['Median House Value'])])]
            npdf = np.array(n)
            list=npdf.tolist()
            list1.append(list[0][1])
#            w.Listbox1.insert(0,list[0][1])
            a = df[(df['City']==list[0][1])].index.tolist()
            df=df.drop(a)
        w.Listbox1.insert(0,"Top 5 cities with most Median House Value:")
        w.Listbox1.insert(1,("1."+list1[0]+"  2."+list1[1]+"  3."+list1[2]+"  4."+list1[3]+"  5."+list1[4]+"  "))
        w.Listbox1.insert(2,'')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import GUI
    GUI.vp_start_gui()


